// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SMATMVC.Models;
using System;

namespace SMATMVC.Migrations
{
    [DbContext(typeof(SiteInfoContext))]
    partial class SiteInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("SMATMVC.Models.SiteInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Creator");

                    b.Property<DateTime?>("LastItemModifiedDate");

                    b.Property<string>("Owners");

                    b.Property<int>("ProposedDisposition");

                    b.Property<string>("SiteCollectionAdmins");

                    b.Property<string>("SiteUrl");

                    b.Property<string>("WebUrl");

                    b.HasKey("ID");

                    b.ToTable("SiteInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
